### ISSUE TITLE
请问有xbox版的吗

### ISSUE THREAD

**Issue by shichaoufo** [xlc520/MaoTV#2]
请问大佬就是这个软件的作者吗，软件确实非常好用啊，有兴趣搞个xbox版吗，没兴趣就当我没说，作为伸手党也不好提太多要求。

**Comment by xlc520** [comment]
> 请问大佬就是这个软件的作者吗，软件确实非常好用啊，有兴趣搞个xbox版吗，没兴趣就当我没说，作为伸手党也不好提太多要求。

我不是作者，只是搬运一个做备份，你可以[看这里](https://github.com/catvod)，或者去telegram群`catvod`问问
