### ISSUE TITLE
请问下这是猫影视官方的发布地址吗

### ISSUE THREAD

**Issue by ymp12345** [xlc520/MaoTV#3]

**Comment by xlc520** [comment]
不是，我是从其他地方搬运的，做个备份，自己用。
>我只是大自然的搬运工，请尊重作者原创！

**Comment by xlc520** [comment]
> _No description provided._

你可以自己去找一下官方发布的地方

**Comment by ymp12345** [comment]
> 不是，我是从其他地方搬运的，做个备份，自己用。
> 
> > 我只是大自然的搬运工，请尊重作者原创！

**Comment by ymp12345** [comment]
额，你也不知道官方发布地址嘛

**Comment by xlc520** [comment]
> 额，你也不知道官方发布地址嘛

对
