### ISSUE TITLE
希望增加缓存功能

### ISSUE THREAD

**Issue by joshatt** [xlc520/MaoTV#4]
看到新增了一个缓存功能, 后来发现是配置缓存. 
希望能增加缓存功能, 接口再好, 也有片源少的片子卡顿的时候, 如果有缓存, 去喝杯水, 回来流畅观看到底, 那就太爽了.
另外, TV硬件有限, 每个片子看完后, 自动清空缓存, 也许应该这样吧

**Comment by xlc520** [comment]
> 

我不是原作，只是从外网搬运，这个建议可以跟作者反馈一下，这是作者[代码仓库](https://github.com/catvod)

**Comment by joshatt** [comment]
谢谢
