### ISSUE TITLE
作者大大，请在猫影视TV播放界面增加四角显示+进度条开关，非常实用。

### ISSUE THREAD

**Issue by xinyi1984** [xlc520/MaoTV#5]
![(JN@MTI}4 %QY4`XWEQ W`M](https://user-images.githubusercontent.com/106141301/170453269-d0cf1f04-5c8c-4375-9581-ca1b8b31d79a.jpg)
![(%_VI(NXPK82D`U(`FB~6ME](https://user-images.githubusercontent.com/106141301/170453357-53013ff8-48b3-42cb-9085-32af6458760e.jpg)

**Comment by xlc520** [comment]
我不是APP作者，只是从外网搬运源，做个备份，这个建议可以跟作者反馈一下，这是作者[代码仓库](https://github.com/catvod)

**Comment by xinyi1984** [comment]
联系不了作者，反馈不了，请你帮忙反馈下。

**Comment by xlc520** [comment]
> 联系不了作者，反馈不了，请你帮忙反馈下。

已经反馈

**Comment by xinyi1984** [comment]
> > 联系不了作者，反馈不了，请你帮忙反馈下。
> 
> 已经反馈

多谢

**Comment by xinyi1984** [comment]
> > > 联系不了作者，反馈不了，请你帮忙反馈下。
> > 
> > 
> > 已经反馈
> 
> 多谢

能把作者的联系推送一下嘛

**Comment by xlc520** [comment]
> 

有tg频道，但是似乎不允许加入了，我没有找到链接

**Comment by xinyi1984** [comment]
> 作者，请在猫影视播放画面中增加四角显示+动画条开关，非常实用



> > > > 联系不了作者，反馈不了，请你帮忙反馈下。
> > > 
> > > 
> > > 已经反馈
> > 
> > 
> > 多谢
> 
> 作者能把的联系一下吗

能发来看下吗

**Comment by xinyi1984** [comment]
> > 作者，请在猫播放画面中增加四角影视显示+动画条开关，非常实用
> 
> > > > > 联系不了作者，反馈不了，请你帮忙反馈下。
> > > > 
> > > > 
> > > > 已经反馈
> > > 
> > > 
> > > 多谢
> > 
> > 
> > 作者能把的联系一下吗
> 
> 能发看下吗
方便qq联系吗 我的qq399232408

**Comment by xlc520** [comment]
![image](https://user-images.githubusercontent.com/56480807/170457925-a23db745-eac2-447f-93c0-c030ec50bcae.png)
