### ISSUE TITLE
作者，请问猫影视tv 你用什么打包的，播放器的布局谁做的

### ISSUE THREAD

**Issue by xinyi1984** [xlc520/MaoTV#7]
作者，请问猫影视tv 你用什么打包的，播放器的布局谁做的，加qq咨询你一下 399232408

**Comment by xlc520** [comment]
我不是作者↓↓
#3 
[#2](https://github.com/xlc520/MaoTV/issues/2#issuecomment-1073231584)

**Comment by xlc520** [comment]
> 能加你qq聊一下吗？

我就保存了自用的播放源，也不会啥开发

**Comment by xinyi1984** [comment]
> > 能加你qq聊一下吗？
> 
> 我就保存了自用的播放源，也不会啥开发
又更新了beta4 是你弄的吗？

**Comment by xlc520** [comment]
作者的代码仓库
https://github.com/catvod

**Comment by xlc520** [comment]
这个我也不知道，毕竟不是开发的
